<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="7" ignored="0" total="7" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="testsuite" duration-ms="110" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
    <groups>
      <group name="regression">
        <method signature="LoginTest.VerifyUserShouldLoginSuccessfullyWithValidCredentials()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="VerifyUserShouldLoginSuccessfullyWithValidCredentials" class="com.demo.nopcommerce.testsuite.LoginTest"/>
        <method signature="LoginTest.verifyUserShouldNavigateToLoginPage()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="verifyUserShouldNavigateToLoginPage" class="com.demo.nopcommerce.testsuite.LoginTest"/>
        <method signature="LoginTest.verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials" class="com.demo.nopcommerce.testsuite.LoginTest"/>
        <method signature="RegistrationTest.VerifyUserNavigateToRegisterPageSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuite.RegistrationTest@402f32ff]" name="VerifyUserNavigateToRegisterPageSuccessfully" class="com.demo.nopcommerce.testsuite.RegistrationTest"/>
        <method signature="RegistrationTest.verifyUserShouldAbleTORegisterSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuite.RegistrationTest@402f32ff]" name="verifyUserShouldAbleTORegisterSuccessfully" class="com.demo.nopcommerce.testsuite.RegistrationTest"/>
        <method signature="TestSuite.verifyProductAddedToShoppingCartSuccessFully()[pri:0, instance:com.demo.nopcommerce.testsuite.TestSuite@573f2bb1]" name="verifyProductAddedToShoppingCartSuccessFully" class="com.demo.nopcommerce.testsuite.TestSuite"/>
        <method signature="TestSuite.verifyProductArrangeInAlphabeticalOrder()[pri:0, instance:com.demo.nopcommerce.testsuite.TestSuite@573f2bb1]" name="verifyProductArrangeInAlphabeticalOrder" class="com.demo.nopcommerce.testsuite.TestSuite"/>
      </group> <!-- regression -->
      <group name="smoke">
        <method signature="LoginTest.verifyUserShouldNavigateToLoginPage()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="verifyUserShouldNavigateToLoginPage" class="com.demo.nopcommerce.testsuite.LoginTest"/>
        <method signature="RegistrationTest.VerifyUserNavigateToRegisterPageSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuite.RegistrationTest@402f32ff]" name="VerifyUserNavigateToRegisterPageSuccessfully" class="com.demo.nopcommerce.testsuite.RegistrationTest"/>
        <method signature="TestSuite.verifyProductArrangeInAlphabeticalOrder()[pri:0, instance:com.demo.nopcommerce.testsuite.TestSuite@573f2bb1]" name="verifyProductArrangeInAlphabeticalOrder" class="com.demo.nopcommerce.testsuite.TestSuite"/>
      </group> <!-- smoke -->
      <group name="sanity">
        <method signature="LoginTest.verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials" class="com.demo.nopcommerce.testsuite.LoginTest"/>
        <method signature="RegistrationTest.verifyUserShouldAbleTORegisterSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuite.RegistrationTest@402f32ff]" name="verifyUserShouldAbleTORegisterSuccessfully" class="com.demo.nopcommerce.testsuite.RegistrationTest"/>
        <method signature="TestSuite.verifyProductAddedToShoppingCartSuccessFully()[pri:0, instance:com.demo.nopcommerce.testsuite.TestSuite@573f2bb1]" name="verifyProductAddedToShoppingCartSuccessFully" class="com.demo.nopcommerce.testsuite.TestSuite"/>
      </group> <!-- sanity -->
    </groups>
    <test name="Sanity Test" duration-ms="110" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
      <class name="com.demo.nopcommerce.testsuite.TestSuite">
        <test-method status="FAIL" signature="verifyProductAddedToShoppingCartSuccessFully()[pri:0, instance:com.demo.nopcommerce.testsuite.TestSuite@573f2bb1]" name="verifyProductAddedToShoppingCartSuccessFully" duration-ms="0" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.TestSuite.verifyProductAddedToShoppingCartSuccessFully(TestSuite.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductAddedToShoppingCartSuccessFully -->
        <test-method status="FAIL" signature="verifyProductArrangeInAlphabeticalOrder()[pri:0, instance:com.demo.nopcommerce.testsuite.TestSuite@573f2bb1]" name="verifyProductArrangeInAlphabeticalOrder" duration-ms="1" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.TestSuite.verifyProductArrangeInAlphabeticalOrder(TestSuite.java:31)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyProductArrangeInAlphabeticalOrder -->
      </class> <!-- com.demo.nopcommerce.testsuite.TestSuite -->
      <class name="com.demo.nopcommerce.testsuite.LoginTest">
        <test-method status="FAIL" signature="VerifyUserShouldLoginSuccessfullyWithValidCredentials()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="VerifyUserShouldLoginSuccessfullyWithValidCredentials" duration-ms="1" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.LoginTest.VerifyUserShouldLoginSuccessfullyWithValidCredentials(LoginTest.java:51)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserShouldLoginSuccessfullyWithValidCredentials -->
        <test-method status="FAIL" signature="verifyUserShouldNavigateToLoginPage()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="verifyUserShouldNavigateToLoginPage" duration-ms="1" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.LoginTest.verifyUserShouldNavigateToLoginPage(LoginTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserShouldNavigateToLoginPage -->
        <test-method status="FAIL" signature="verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials()[pri:0, instance:com.demo.nopcommerce.testsuite.LoginTest@5ae9a829]" name="verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials" duration-ms="3" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.LoginTest.verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials(LoginTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserShouldNotLoginSuccessfullyWithInvalidCredentials -->
      </class> <!-- com.demo.nopcommerce.testsuite.LoginTest -->
      <class name="com.demo.nopcommerce.testsuite.RegistrationTest">
        <test-method status="FAIL" signature="VerifyUserNavigateToRegisterPageSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuite.RegistrationTest@402f32ff]" name="VerifyUserNavigateToRegisterPageSuccessfully" duration-ms="32" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.RegistrationTest.VerifyUserNavigateToRegisterPageSuccessfully(RegistrationTest.java:29)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- VerifyUserNavigateToRegisterPageSuccessfully -->
        <test-method status="FAIL" signature="verifyUserShouldAbleTORegisterSuccessfully()[pri:0, instance:com.demo.nopcommerce.testsuite.RegistrationTest@402f32ff]" name="verifyUserShouldAbleTORegisterSuccessfully" duration-ms="1" started-at="2020-12-09T11:32:05Z" finished-at="2020-12-09T11:32:05Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
at com.demo.nopcommerce.testsuite.RegistrationTest.verifyUserShouldAbleTORegisterSuccessfully(RegistrationTest.java:37)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:110)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyUserShouldAbleTORegisterSuccessfully -->
      </class> <!-- com.demo.nopcommerce.testsuite.RegistrationTest -->
    </test> <!-- Sanity Test -->
  </suite> <!-- testsuite -->
</testng-results>
